remote_theme: pmarsceill/just-the-docs
#theme: "just-the-docs"
title: "BibExplorer"
description: "A tool to process curricula, extract article meta-data from various APIs, and calculate bibliometric indicators"

search_enabled: true

aux_links:
  "mdsplit on github":
    - "//github.com/alandefreitas/bibexplorer"

aux_links_new_tab: true

footer_content: "Copyright &copy; Alan Freitas. Distributed by an <a href=\"https://github.com/alandefreitas/bibexplorer/tree/master/LICENSE.txt\">MIT license.</a>"
